[package]
name = "writing-an-interpreter-in-go"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.0.0"
colored = "2.0.0"
ctrlc = "3.4.0"
anyhow = "1.0.71"
thiserror = "1.0.40"